public class Recursionblocker {
	Public static Boolean firstcall=false;
	Public static Integer quoteTrigger = 0 ;
	Public static Integer quoteLineTrigger = 0;
	Public static Integer opportunityTrigger = 0;
	Public static Integer acountTrigger = 0;
	Public static Integer attachedDocumentTrigger = 0;
	Public static Integer caseTrigger = 0;
	Public static Integer contactTrigger = 0;
	Public static Integer productOptionTrigger = 0;
    Public static Integer OpportunityContactRoleTrigger = 0;
	Public static Integer leadTrigger = 0;
	Public static Integer userTerritory2AssociationTrigger = 0;			
}